### PR TITLE
Properly scope InitOpenGL to fix linking

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Review by AmrikSadhra — APPROVED** [review]
Matches a commit I have locally + some other goodies, but let's fix CI quickly. Thanks!

**Comment by janisozaur** [comment]
Are you hiding more stuff away from us? :see_no_evil:

**Comment by janisozaur** [comment]
MSVC build has failed, others are building fine on Azure.

All the MSVC errors are of type:
`src\RaceNet\TrainingGround.cpp(163,0): Error C2131: expression did not evaluate to a constant`

**Comment by AmrikSadhra** [comment]
Hahaha! Just a little :P Will fix this build error when back on desktop tomorrow morning.

**Pull request closed without merging**
